name: Run checks

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: check formatting via nox
        run: |
          python -m pip install nox
          python -m nox -s format
  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: run mypy via nox
        run: |
          python -m pip install nox
          python -m nox -s mypy